/** Strings for the public order flow and confirmation page. */
export const OT = {
  ar: {
    kicker: "اطلب دعوتك",
    title: "خلّينا نجهّز دعوة فرحكم",
    intro: "اختاروا الطريقة اللي تريحكم:",
    onlineTitle: "اطلب أونلاين",
    onlineBody: "اختاروا التصميم واملوا التفاصيل في دقيقتين، وفريقنا يتواصل معاكم للتأكيد.",
    onlineCta: "ابدأ الطلب",
    chatTitle: "كلّمنا مباشرة",
    chatBody: "عايزين تسألوا الأول؟ ابعتولنا على واتساب ونرد عليكم فوراً.",
    chatCta: "افتح واتساب",
    steps: ["التصميم", "التفاصيل", "الصور والطلبات", "المراجعة"],
    chooseDesign: "اختاروا التصميم",
    preview: "معاينة",
    selected: "تم الاختيار",
    couple: "العروسين",
    groom: "اسم العريس",
    bride: "اسم العروسة",
    contact: "التواصل",
    whatsapp: "رقم واتساب",
    whatsappHint: "هنتواصل معاكم على الرقم ده لتأكيد الطلب",
    email: "البريد الإلكتروني (اختياري)",
    event: "تفاصيل المناسبة",
    eventType: "نوع المناسبة",
    date: "التاريخ",
    time: "الساعة",
    city: "المدينة",
    venue: "اسم القاعة / المكان",
    address: "العنوان",
    maps: "رابط خرائط جوجل (اختياري)",
    guests: "عدد المعازيم التقريبي (اختياري)",
    prefs: "تفضيلات التصميم",
    language: "لغة الدعوة",
    langs: { ar: "عربي", en: "English", both: "عربي وإنجليزي" },
    music: "الموسيقى",
    sections: "الأقسام اللي تحبوها",
    colors: "ألوان أو ستايل مفضل (اختياري)",
    colorsPh: "مثلاً: دهبي وأبيض، هادي وكلاسيك…",
    wording: "صياغة أو آية أو جملة تحبوها (اختياري)",
    photos: "الصور (اختياري)",
    photosHint: "صوركم وصور القاعة بتخلي الدعوة أحلى. نقدر نضيفها بعدين كمان.",
    couplePhotos: "صور العروسين",
    venuePhotos: "صور أو سكرين شوت للقاعة",
    addPhotos: "إضافة صور",
    uploading: "جارٍ الرفع…",
    remove: "حذف",
    notes: "أي ملاحظات أو طلبات إضافية",
    notesPh: "اكتبوا أي حاجة تهمكم…",
    next: "التالي",
    back: "رجوع",
    review: "راجعوا طلبكم",
    reviewHint: "اتأكدوا إن كل حاجة مظبوطة قبل الإرسال.",
    edit: "تعديل",
    consent: "بإرسال الطلب، أنتم موافقين إن فريق مبروك يتواصل معاكم على واتساب.",
    submit: "إرسال الطلب",
    sending: "جارٍ الإرسال…",
    none: "—",
    required: "من فضلك اكملوا الحقول المطلوبة",
    invalidPhone: "رقم واتساب غير صحيح",
    rateLimited: "استقبلنا طلبات كتير من الجهاز ده. جربوا بعد شوية أو كلمونا على واتساب.",
    failed: "حصلت مشكلة، حاولوا تاني أو كلمونا على واتساب.",
    tooLarge: "الصورة أكبر من ٤ ميجا",
    draftSaved: "بنحفظ طلبكم تلقائياً على الجهاز ده",
    // Confirmation
    thanks: "استلمنا طلبكم 🤍",
    refLabel: "رقم الطلب",
    nextTitle: "إيه اللي هيحصل دلوقتي؟",
    next1: "فريقنا هيراجع الطلب ويتواصل معاكم على واتساب للتأكيد.",
    next2: "بعد التأكيد بنجهّز الدعوة ونبعتلكم معاينة.",
    next3: "بعد موافقتكم بتستلموا الرابط النهائي جاهز للمشاركة.",
    yourDetails: "تفاصيل الطلب",
    contactUs: "عايزين تكلمونا دلوقتي؟",
    ourNumber: "رقمنا على واتساب",
    chatNow: "كلّمنا على واتساب",
    backHome: "الرجوع للتصاميم",
    notFound: "الطلب غير موجود",
    design: "التصميم",
    photosCount: "صور مرفقة",
  },
  en: {
    kicker: "Order your invitation",
    title: "Let's create your wedding invitation",
    intro: "Choose whichever suits you:",
    onlineTitle: "Order online",
    onlineBody: "Pick a design and fill in your details in two minutes. Our team will contact you to confirm.",
    onlineCta: "Start your order",
    chatTitle: "Talk to us directly",
    chatBody: "Questions first? Message us on WhatsApp and we'll reply right away.",
    chatCta: "Open WhatsApp",
    steps: ["Design", "Details", "Photos & wishes", "Review"],
    chooseDesign: "Choose your design",
    preview: "Preview",
    selected: "Selected",
    couple: "The couple",
    groom: "Groom's name",
    bride: "Bride's name",
    contact: "Contact",
    whatsapp: "WhatsApp number",
    whatsappHint: "We'll contact you on this number to confirm your order",
    email: "Email (optional)",
    event: "Event details",
    eventType: "Event type",
    date: "Date",
    time: "Time",
    city: "City",
    venue: "Venue name",
    address: "Address",
    maps: "Google Maps link (optional)",
    guests: "Approx. number of guests (optional)",
    prefs: "Design preferences",
    language: "Invitation language",
    langs: { ar: "Arabic", en: "English", both: "Arabic & English" },
    music: "Music",
    sections: "Sections you'd like",
    colors: "Preferred colors or style (optional)",
    colorsPh: "e.g. gold & white, calm and classic…",
    wording: "Wording, verse or a line you love (optional)",
    photos: "Photos (optional)",
    photosHint: "Your photos and venue pictures make the invitation shine. You can also send them later.",
    couplePhotos: "Couple photos",
    venuePhotos: "Venue photos or screenshots",
    addPhotos: "Add photos",
    uploading: "Uploading…",
    remove: "Remove",
    notes: "Anything else we should know",
    notesPh: "Tell us anything that matters to you…",
    next: "Next",
    back: "Back",
    review: "Review your order",
    reviewHint: "Make sure everything looks right before sending.",
    edit: "Edit",
    consent: "By sending this order you agree that the Mabrouk team may contact you on WhatsApp.",
    submit: "Send order",
    sending: "Sending…",
    none: "—",
    required: "Please complete the required fields",
    invalidPhone: "That WhatsApp number doesn't look right",
    rateLimited: "We've received many orders from this device. Please try again later or message us on WhatsApp.",
    failed: "Something went wrong. Please try again or message us on WhatsApp.",
    tooLarge: "Photo is larger than 4 MB",
    draftSaved: "Your order is saved on this device as you type",
    thanks: "We've received your order 🤍",
    refLabel: "Order reference",
    nextTitle: "What happens next?",
    next1: "Our team reviews your order and contacts you on WhatsApp to confirm.",
    next2: "Once confirmed, we prepare your invitation and send you a preview.",
    next3: "After your approval, you receive the final link, ready to share.",
    yourDetails: "Your order",
    contactUs: "Want to talk to us now?",
    ourNumber: "Our WhatsApp",
    chatNow: "Chat on WhatsApp",
    backHome: "Back to designs",
    notFound: "Order not found",
    design: "Design",
    photosCount: "photos attached",
  },
} as const;

export const COUNTRY_CODES = [
  { code: "20", label: "🇪🇬 +20" },
  { code: "966", label: "🇸🇦 +966" },
  { code: "971", label: "🇦🇪 +971" },
  { code: "965", label: "🇰🇼 +965" },
  { code: "974", label: "🇶🇦 +974" },
  { code: "973", label: "🇧🇭 +973" },
  { code: "968", label: "🇴🇲 +968" },
  { code: "962", label: "🇯🇴 +962" },
  { code: "44", label: "🇬🇧 +44" },
  { code: "1", label: "🇺🇸 +1" },
  { code: "49", label: "🇩🇪 +49" },
];
